export const PitcherSchema = {
  last_name: String,
  first_name: String,
  display_name: String,
  pitch_order: Number,
  win: Boolean,
  loss: Boolean,
  save: Boolean,
  hold: Boolean,
  era: Number,
  whip: Number,
  innings_pitched: Number,
  hits_allowed: Number,
  runs_allowed: Number,
  earned_runs: Number,
  walks: Number,
  intentional_walks: Number,
  strike_outs: Number,
  home_runs_allowed: Number,
  pitch_count: Number,
  pitches_strikes: Number,
  wild_pitches: Number,
  hit_by_pitch: Number,
  errors: Number,
  team_abbreviation: String,
};
