import { TotalsSchema } from "./Totals";
export const PlayerStatsSchema = {
  last_name: String,
  first_name: String,
  display_name: String,
  position: String,
  //   minutes: Number,
  //   points: Number,
  //   assists: Number,
  //   turnovers: Number,
  //   steals: Number,
  //   blocks: Number,
  //   field_goals_attempted: Number,
  //   field_goals_made: Number,
  //   three_point_field_goals_attempted: Number,
  //   three_point_field_goals_made: Number,
  //   free_throws_attempted: Number,
  //   free_throws_made: Number,
  //   defensive_rebounds: Number,
  //   offensive_rebounds: Number,
  //   personal_fouls: Number,
  //   field_goal_percentage: Number,
  //   three_point_percentage: Number,
  //   free_throw_percentage: Number,
  team_abbreviation: { type: String, maxLength: 3 },
  is_Starter: Boolean,
  TotalsSchema,
};
